name: Automated API tests using Postman CLI

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key PMAK-65a2370440a3d3003fe53e82-fbd33b57665acead29b71f5aae9d912807
      - name: Run API tests
        run: |
          postman collection run "28237644-893dbac7-cbaf-43cb-a241-5a46987866f7"


name: Postman Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '14'

    - name: Install Newman
      run: npm install -g newman

    - name: Run Postman Tests
      run: newman run "Book collection.postman_collection.json" -e "new_orders.json"
